### ISSUE TITLE
Signup Questions

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#106]
As part of anti-spambot measures, on signup, require the user to enter the answer to a random question.  These questions (five of them) should be kept in the settings file, per discussion with @Deleetdk.

**Comment by hmcclungiii** [comment]
Questions are in settings.py SPAMBOT_QUESTIONS dictionary.

![screenshot 113](https://user-images.githubusercontent.com/6778244/53836227-6de8ea00-3f5d-11e9-9b31-e295bada1c4f.png)

closed by commit 980d7c4a08dc3f82da7f1a5dafe18428a9e0e4a3

**Comment by Deleetdk** [comment]
Looks good
