### ISSUE TITLE
Google Captcha

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#107]
Add Google CAPTCHA box to both signup form and login.

**Comment by hmcclungiii** [comment]
commit bfb4b9f30544240d2217c9e32b5b3002a6963f3b closes this

![screenshot 114](https://user-images.githubusercontent.com/6778244/53921202-921bf800-403d-11e9-8f2b-892d51dad63a.png)

**Comment by hmcclungiii** [comment]
![screenshot 116](https://user-images.githubusercontent.com/6778244/53921314-f50d8f00-403d-11e9-9360-72bd47a7fab8.png)

**Comment by Deleetdk** [comment]
@hmcclungiii do we need CAPTCHA for logins? I guess one can force it once in a while, but generally users just stay logged in via cookies.

**Comment by hmcclungiii** [comment]
Users will stay logged in, until they log out, so they won't need to login every time they visit the site.
