### ISSUE TITLE
Title Formatting Filters

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#111]
Add filters from MQ to use [i] and [b] to titles for italics and bold.

**Comment by hmcclungiii** [comment]
Quick question: Should this be for both titles in the normal website, and the forums also?

**Comment by hmcclungiii** [comment]
I've got the filters applied to publication title and journal name, do we need it in the forums also?

**Comment by hmcclungiii** [comment]
![Screenshot (133)_LI](https://user-images.githubusercontent.com/6778244/54831213-549ba980-4c90-11e9-9427-a2a2e3a4414b.jpg)
![Screenshot (134)_LI](https://user-images.githubusercontent.com/6778244/54831215-549ba980-4c90-11e9-8151-f97c09b8efc8.jpg)

**Comment by Deleetdk** [comment]
>I've got the filters applied to publication title and journal name, do we need it in the forums also?

Probably not.
