### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#12]
We should use HTTPS.

**Comment by Deleetdk** [comment]
Bounty: 150 DKK.
@onbjerg

**Comment by onbjerg** [comment]
Can be done using LetsEncrypt. I will look into it if you green light it, unless you want to spend money on a certificate.

**Comment by Deleetdk** [comment]
Greenlighted.

**Comment by onbjerg** [comment]
Waiting for technical support. I forgot my password on the VPS.

**Comment by onbjerg** [comment]
Fixed. Please don't touch the configuration files unless you know what you are doing(TM).

**Comment by Deleetdk** [comment]
I never know what I'm doing, but I take backups! Unless I forget and cry like a little girl when I lose all my data.

**Comment by Deleetdk** [comment]
@onbjerg You have forgotten to renew it. Since you didn't tell me what you did, it's a little difficult to fix.

**Comment by Deleetdk** [comment]
Looks like you used `certbot`, but used the alternative name for it, `letsencrypt`. So my attempt at renewing failed with command not found.

https://certbot.eff.org/docs/using.html

To renew:

```
sudo letsencrypt renew
apache_restart
```

The second is part of my .bashrc and is actually `sudo /etc/init.d/apache2 restart`.

Browser verification.

![letsencrypt](https://cloud.githubusercontent.com/assets/6759913/22091570/d149cd5e-ddf7-11e6-8258-62d4891535ef.png)

Please confirm this is how to do things.

**Comment by onbjerg** [comment]
Confirmed.
