### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#13]
The server cannot send emails right now because this has not been setup. So users cannot reset passwords or make users on the forum (never get the activation email). Pretty bad bug!

**Comment by Deleetdk** [comment]
Bounty: 150 DKK

**Comment by onbjerg** [comment]
We probably need to configure Django to send mails. I don't know if we can use sendmail as PHP can. Would be a fast solution if we could.

**Comment by onbjerg** [comment]
Closeable when username/password is filled in ``settings.py``.

**Comment by onbjerg** [comment]
Fixed. ``sendmail`` was not installed, so I installed it and restarted php and Apache.
