### ISSUE TITLE
Implement system for automatic DOI assignment

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#14]
When DOIs have been bought (my task), make a system for setting them on the papers automatically.

**Comment by Deleetdk** [comment]
We now have DOIs via crossref. There is a field for storing these, but no automatic system for generating them. Given the low publication rate of OP, it doesn't seem worth the time to implement an automatic system for requesitng DOIs via their API.

**Comment by hmcclungiii** [comment]
Basing the value of an automated system on current low publication rates may be cutting yourself short?  Do you expect an increase in publication rates?  I certainly do.  If rates may increase in the near future, do you think it's a good idea to be prepared?

**Comment by Deleetdk** [comment]
I don't expect a large increase in the near future, no. So this feature will not be necessary for a while. I would do more networking to get more submissions, but for now I'm quite busy with work on the biotech company, so have less time to devote to research and promotion.

**Comment by hmcclungiii** [comment]
@Deleetdk You have purchased this system.  The DOI field is in the database.  We need the meta tag **DC.Identifier.DOI** added to the page head, and the DOI should be displayed where?  I'm thinking right under the Download Paper button, before the keywords? 
![fireshot capture 1 - net fiscal contributions of immigrant groups _ - https___openpsych net_paper_53](https://user-images.githubusercontent.com/6778244/30604336-86d984fc-9d38-11e7-85b6-c5a56c9a5a11.png)
