### ISSUE TITLE
Use layout template

### ISSUE THREAD

**Issue by onbjerg** [openpsych/django#29]
We can simplify some of our templates by using template extension from a master layout template instead of including the header and footer partial all the time.

**Comment by Deleetdk** [comment]
Pretty little gain: save 2 lines of code per template!

**Comment by onbjerg** [comment]
Sure, but might be more gain in the long run. Setting this to lowest.

**Comment by hmcclungiii** [comment]
This is partially what I was referring to in #59.  There is more to gain than just a few lines of code.  This is in the hmcclungiii-001 branch, which I'll probably be merging shortly.

**Comment by Deleetdk** [comment]
Fine by me.
