### ISSUE TITLE
Better spam/antibot filter

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#32]
Right now, most new users on the forum are spammers/bots. Perhaps it's possible to find a better filter. From looking at the profiles, probably a good chunk of them were added manually by someone. We cannot really guard against that easily. One could make an "apply to become a member" feature, but this would discourage new users and add work for admins.

E.g. look at recent new users:

https://www.openpsych.net/forum/memberlist.php

Thoughts?

**Comment by hmcclungiii** [comment]
Since implementing the Google reCaptcha, random question and IP Blacklisting (in which singular IP addresses can also be added), should this now be closed?

**Comment by Deleetdk** [comment]
Yeah, probably.
