### ISSUE TITLE
Fix title in Person view

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#36]
https://openpsych.net/person/1

`<title>Emil O. W. Kirkegaard&#39;s&#39; profile</title>`

**Comment by hmcclungiii** [comment]
I believe you mean that second single quote at the end of the name.  Should probably capitalize the word profile also.  So instead of **Emil O. W. Kirkegaard's'** profile it should say **Emil O. W. Kirkegaard's** Profile.

**Comment by Deleetdk** [comment]
If this is done, please attach screenshot of the result, and close issue.

**Comment by hmcclungiii** [comment]
# Closing Issue #36.

Notice the title of the page being displayed in the top of the tab of Chrome.  In Firefox the tab isn't big enough to fit Emil's name so the difference isn't noticeable.
## **Before**
![sketch 3a](https://user-images.githubusercontent.com/6778244/29753321-1685f97c-8b3d-11e7-88c1-f77523bfb884.png)
## **After**
![sketch 3b](https://user-images.githubusercontent.com/6778244/29753322-168a495a-8b3d-11e7-8408-d605d8dae6e4.png)
