### ISSUE TITLE
Add SCSS Support

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#60]
To be able to use the scss preprocessor to generate our CSS files.  This will improve and make styling more efficient now and in the future.

**Comment by hmcclungiii** [comment]
I'm still working on this.

**Comment by Deleetdk** [comment]
Never heard of SCSS. Why do we need a CSS preprocessor?

https://stackoverflow.com/questions/5654447/whats-the-difference-between-scss-and-sass

**Comment by hmcclungiii** [comment]
I believe this was explained sufficiently in chat, but if you'd like me to post an explanation here just let me know.  My apologies for using SASS and SCSS as interchangeable terms.  I am referring to SCSS and will try to refrain from using the former term in the future, as SASS implements different syntactical sugar.
