### ISSUE TITLE
On Journal Page, Person Links are Wrong

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#64]
This problem is showing on the master branch:

Steps to reproduce ...
1) Click Journals link in the top nav bar.
2) Click the first journal link, Open Differential Psychology
3) Under "Publications in this journal", the person links are incorrect.

![inkedemilia2_li](https://user-images.githubusercontent.com/6778244/29982254-fbf1209c-8f1e-11e7-9e1a-65cd15532de0.jpg)

**Comment by Deleetdk** [comment]
Yeah, this one is clearly broken. Please fix immediately.
