### ISSUE TITLE
Some url issues

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#65]
Looking over Google webmaster's error report. I see a lot of irrelevant issues having to do with previous URLs from the old wordpress sites. 

![old urls google](https://user-images.githubusercontent.com/6759913/29983612-bc44c6b4-8f24-11e7-9d90-ccc244a68414.png)

However, there's a few current issues.

- https://openpsych.net/about/, should redirect to https://openpsych.net/about
- https://openpsych.net/journals/ as above

Solving these should be a fairly minor task with the `urls.py`.

**Comment by hmcclungiii** [comment]
Also https://openpsych.net/for_reviewers/ as above
