### ISSUE TITLE
Conflicting names between MyBB forums and new forums.

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#74]
We can't have _forum_ in the urls.py or views.py modules because it causes a conflict with the extant MyBB forum links.

Making the safest assumption about the destiny of the MyBB forums, I need to change the forum namespace in the forums app.  This will allow us to retain the old forums, in the event @Deleetdk wishes to keep them online for a time after release of the new forums.

**Comment by Deleetdk** [comment]
Why not just implement a parser for the old forum URLs and redirect those to the corresponding new locations? I did that for the publication urls. I don't see the issue. In the dev version, move the mybb to some other, like /oldforum. Then write a parser for calls to /forum that follow the mybb pattern and redirect those to the new forum's equivalent material (as far as possible, i.e. disregard mybb non-content stuff like calendars).

**Comment by hmcclungiii** [comment]
There isn't an issue.  This is for documentation purposes, as you requested.
