### ISSUE TITLE
Add ISSNs

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#75]
We have ISSNs. They are in the database already. Please add them where appropriate. This means at least at the journal overview pages, and maybe more discretely also at the Paper page.

**Comment by hmcclungiii** [comment]
When I look at other sites having the ISSN displayed, the ISSN number is preceded by Quarterly, Monthly, Bimonthly, etc.  For now, the publication frequency will be ignored, as it is currently not in the database.  Unless @Deleetdk would prefer I go ahead and add this field.

**Comment by Deleetdk** [comment]
We don't have issues and volumes. If they must be used in some context, I think I put it in 1, 1 hardcoded somewhere.
