### ISSUE TITLE
Cron Job for Automatic SSL Renewal

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#79]
After fixing the SSL Certificates #80, a daily cron job needs to be setup to check the status of the LetsEncrypt SSL certificates and renew them when necessary.

When the certificates are renewed, a notification email should be sent to @Deleetdk at the.dfx@gmail.com.

**Comment by Deleetdk** [comment]
I did set up a cron job for this, but somehow it is not working. Did you find the error?

**Comment by Deleetdk** [comment]
I finally found the error. root password was expired!

https://askubuntu.com/a/108964/573611
