### ISSUE TITLE
Automatic IP Blocking

### ISSUE THREAD

**Issue by hmcclungiii** [openpsych/django#81]
There are a large number of requests, apparently from spammers, attempting to gain access to the server.  While these requests are being blocked and are essentially harmless, the IP addresses involved should be automatically blacklisted after x number of declined attempts.

**Comment by Deleetdk** [comment]
One way would be to parse the log file to extract the IPs and block them if they reach some request limit.

**Comment by hmcclungiii** [comment]
That would require a cron job.  In most cases, as far as I know, a cron job wouldn't be able to stop them immediately.  

I was thinking about logging IP's and login failures in the database, and then after so many failure attempts they are blocked for a certain amount of time.  After being blocked xx times, they go on a black list from which they can not be removed without contacting you.

You may also want an email each time one of these actions occur.

And perhaps we should also implement the Google Captcha?

**Comment by Deleetdk** [comment]
I was assuming that you would implement Captcha for the registration process. Note that spammers sometimes have people working low wage to solve captchas on forums. Since after the users get in, they can spam away. Annoying.

**Comment by hmcclungiii** [comment]
Yes, both for registration and login.  And of course we'd be able to access the blacklist from the back-end admin site.

**Comment by hmcclungiii** [comment]
We now have IP blacklisting (currently for Russia and China, but IPs can be added via the admin portal).  We now have Google Captcha on Signup and Login.  Last but not least, we have the random question & answer on signup.

Unless anyone objects, I'm going to go ahead and close this issue.

**Comment by Deleetdk** [comment]
I think leave the login working, but disable user creation for these semi-blacklisted countries. Basically, they try to make a bunch of users, and we don't wanna deal with these. However, I have made some users manually for some people, and they should be able to login from Russia and China.
