### ISSUE TITLE
PDF downloads don't work

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#86]
Recent push broke the downloads. Please fix ASAP.

Also, please make a test for this you can run before pushing to production (i.e. download some random papers from site, compare to known versions).

E.g.

https://openpsych.net/files/papers/Carl_2018b_lVzYOEW.pdf

![screenshot from 2018-11-30 13-06-52](https://user-images.githubusercontent.com/6759913/49306647-d2009b80-f4a0-11e8-82d5-784e95ab50cf.png)

**Comment by hmcclungiii** [comment]
I haven't updated the server with the most recent git commits.  Checking out the problem here.

**Comment by hmcclungiii** [comment]
Lord have mercy, it's the Debug problem again.  I set `Debug=True` and the papers work again.  Reopening #53

**Comment by Deleetdk** [comment]
Sounds like you need to make a production-side test script too, that you run after passing tests locally and pushing to production.
