### ISSUE TITLE
User chosen profile pictures

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#95]
Should be possible to upload a small picture.

**Comment by hmcclungiii** [comment]
![profile](https://user-images.githubusercontent.com/6778244/53054494-8099f400-3472-11e9-9d75-f30b2db94ca3.png)
![change_avatar](https://user-images.githubusercontent.com/6778244/53054498-8263b780-3472-11e9-8c76-73b87bc09fc4.png)
![on_threads_posts](https://user-images.githubusercontent.com/6778244/53054501-8263b780-3472-11e9-97ee-f08c3720b247.png)
