### ISSUE TITLE
Change forum in admin has errors

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#96]
There's a lot of required fields where nothing should be required.

https://beta.openpsych.net/admin/forums/forum/229/change/

Also, a lot of these fields are editable, but should not be. E.g. thread count is clearly a value computed from the database, not something users are supposed to be able to change.

**Comment by Deleetdk** [comment]
Please remember to post screenshots of stuff you fixed. Good habit so I can follow what you are doing.

**Comment by hmcclungiii** [comment]
ok
![fireshot capture 028 - change forum i o_ - https___beta openpsych net_admin_forums_forum_248_change_](https://user-images.githubusercontent.com/6778244/52590589-ac343300-2e0f-11e9-8879-6dd989ac3246.png)
